apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  capacity:
    storage: 1Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /nfs
    server: <NFS_SERVER_IP>
  persistentVolumeReclaimPolicy: Recycle

